# Generated by Django 4.2.11 on 2026-02-08 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('type_logement', models.CharField(choices=[('Studio', 'Studio'), ('Chambre', 'chambre'), ('T2', 'T2'), ('T3', 'T3'), ('Villa', 'Villa')], max_length=20)),
                ('quartier', models.CharField(max_length=50)),
                ('prix', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='appartements/')),
                ('contact_proprietaire', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppartementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='appartements/')),
                ('is_main', models.BooleanField(default=False)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appartement.appartement')),
            ],
        ),
    ]
