# Generated by Django 4.2.11 on 2026-02-08 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appartement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartements', to=settings.AUTH_USER_MODEL),
        ),
    ]
